services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app  
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5434"